version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/deluge.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: deluge
build:
  run_buildscript: false
images:
  - id: deluge
    target: service
    service: deluge
    source: linuxserver/deluge
    channel: stable
    sort: semver
    tag_regex: '^v?\d+\.\d+\.\d+$'
    exclude_regex: '^(18|19|20)\.'
    delivery:
      mode: mirror
stores:
  official:
    enabled: false
    skip_if_version_exists: true
  private:
    enabled: true
    skip_if_version_exists: true
    name: Deluge
    summary: "轻量级、自由软件、跨平台的 BitTorrent 客户端"
