lzc-sdk-version: "0.1"
name: Deluge
package: cloud.lazycat.app.deluge
version: 2.1.1
description: BitTorge是一个轻量级的、自由软件的、跨平台的BitTorrent客户端
homepage: https://deluge-torrent.org
author: deluge
application:
  subdomain: deluge
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://deluge.cloud.lazycat.app.deluge.lzcapp:8112/
  ingress:
    - protocol: tcp
      port: 6881
      service: deluge
    - protocol: udp
      port: 6881
      service: deluge
    - protocol: tcp
      port: 58846
      service: deluge
services:
  deluge:
    image: registry.lazycat.cloud/czyt/linuxserver/deluge:6bdbeda8660d300c
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/downloads:/downloads
